GymApp/Models/Returns.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GymApp.Models
{
    public class Returns
    {

        [DatabaseGenerated(DatabaseGeneratedOption.Identity), Key]
        public int ReturnId { get; set; }
        public int Id { get; set; }
        public Order Order { get; set; }
        public string ReturnReason { get; set; }
        public string RequestedBy { get; set; }
        public bool IsApproved { get; set; }
        public string imageUrl { get; set; }
    }
}

GymApp/Controllers/ReturnsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymApp.Models;

namespace GymApp.Controllers
{
    public class ReturnsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Returns
        public ActionResult Index()
        {
            var returns = db.Returns.Include(r => r.Order);
            return View(returns.ToList());
        }

        public ActionResult OrderIndex()
        {
            return View(db.orders.ToList());
        }


        // GET: Returns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Returns returns = db.Returns.Find(id);
            if (returns == null)
            {
                return HttpNotFound();
            }
            ViewBag.Url=returns.imageUrl;
            return View(returns);
        }

        // GET: Returns/Create
        public ActionResult Create(int? id)
        {
            ViewBag.Id = new SelectList(db.orders, "Id", "DeliveryFirstName");
            return View();
        }

        // POST: Returns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReturnId,Id,ReturnReason,RequestedBy,IsApproved,imageUrl")] Returns returns,string ImageData)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase fileBase = Request.Files["ImageFile"];
                if (fileBase !=null && fileBase.ContentLength >0 )
                {
                    byte[] fileBytes; 
                    using (BinaryReader reader = new BinaryReader(fileBase.InputStream))
                    {
                        fileBytes= reader.ReadBytes(fileBase.ContentLength);
                    }
                    string base64String = Convert.ToBase64String(fileBytes);
                    returns.imageUrl=base64String;
                }
                returns.IsApproved = false;
                returns.RequestedBy=User.Identity.Name;
                db.Returns.Add(returns);
                db.SaveChanges();
                return RedirectToAction("OrderIndex");

            }
            

            ViewBag.Id = new SelectList(db.orders, "Id", "DeliveryFirstName", returns.Id);
            return View(returns);
        }

        public ActionResult Approve(int? id)
        {
            Returns returns = db.Returns.Find(id);
            returns.IsApproved = true;
            db.SaveChanges();
            return RedirectToAction("Index", new { successMessage = "Done for now" });
        }


        // GET: Returns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Returns returns = db.Returns.Find(id);
            if (returns == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = new SelectList(db.orders, "Id", "DeliveryFirstName", returns.Id);
            return View(returns);
        }

        // POST: Returns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReturnId,Id,ReturnReason,RequestedBy,IsApproved,imageUrl")] Returns returns)
        {
            if (ModelState.IsValid)
            {
                db.Entry(returns).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.orders, "Id", "DeliveryFirstName", returns.Id);
            return View(returns);
        }

        // GET: Returns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Returns returns = db.Returns.Find(id);
            if (returns == null)
            {
                return HttpNotFound();
            }
            return View(returns);
        }

        // POST: Returns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Returns returns = db.Returns.Find(id);
            db.Returns.Remove(returns);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GymApp/Views/Returns/Create.cshtml
@model GymApp.Models.Returns

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Returns", FormMethod.Post,new {enctype="multipart/form-data",@class="create-form"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Returns</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="display:none">

            @Html.LabelFor(model => model.Id, "Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        
       




        <div class="form-group">
            @Html.LabelFor(model => model.ReturnReason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnReason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnReason, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <input type="file" name="ImageFile" id="ImageFile" />
        </div>
       


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GymApp/Views/Returns/Delete.cshtml
@model GymApp.Models.Returns

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Returns</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.DeliveryFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.DeliveryFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnReason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnReason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imageUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GymApp/Views/Returns/Details.cshtml
@model GymApp.Models.Returns

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>





<div>
    <h4>Returns</h4>

    <center>
        <img src="data:image/png;base64,@ViewBag.Url" alt="Alternate Text" height="250" width="250" />
    </center>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Order.DeliveryFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Order.DeliveryFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnReason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnReason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsApproved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsApproved)
        </dd>





    </dl>
</div>

<center>
    @Html.ActionLink("Approve","Approve", new {id=Model.ReturnId})
</center>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.ReturnId }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

GymApp/Views/Returns/Edit.cshtml
@model GymApp.Models.Returns

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Returns</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReturnId)

        <div class="form-group">
            @Html.LabelFor(model => model.Id, "Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnReason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnReason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnReason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsApproved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsApproved)
                    @Html.ValidationMessageFor(model => model.IsApproved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GymApp/Views/Returns/Index.cshtml
@model IEnumerable<GymApp.Models.Returns>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdminPage.cshtml";
}
@section scripts{
    <!-- Toastr CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

    <!-- Toastr JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script>// Define the showSuccessMessage function
        function showSuccessMessage(message) {
            toastr.success(message);
        }

        // Handle the Toastr notification.
        $(document).ready(function () {
            // Check if a success message exists in the query string (added after redirection).
            var urlParams = new URLSearchParams(window.location.search);
            if (urlParams.has("successMessage")) {
                var successMessage = urlParams.get("successMessage");
                showSuccessMessage(successMessage);
            }
        });</script>
    }
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Order.DeliveryFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReturnReason)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsApproved)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Order.DeliveryFirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReturnReason)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsApproved)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ReturnId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ReturnId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ReturnId })
                </td>
            </tr>
        }

    </table>

GymApp/Views/Returns/OrderIndex.cshtml
@model IEnumerable<GymApp.Models.Order>

@{
    ViewBag.Title = "OrderIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>OrderIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.prodcts.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order_Date)
        </th>
       
        <th>
            @Html.DisplayNameFor(model => model.IsReceived)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.prodcts.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qty)
        </td>
     
        <td>
            @Html.DisplayFor(modelItem => item.Order_Date)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.IsReceived)
        </td>
       
        <td>
            @Html.ActionLink("Return Item", "Create", new { id = item.Id }) |
           
           
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>