GymApp/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace GymApp.Models
{
    public class Vehicle
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Display(Name = "Vehicle Name")]
        public string VehicleName { get; set; }
        [Display(Name = "Vehicle Color")]
        public string VehicleColor { get; set; }
        [Display(Name = "Number Plate")]
        public string NumberPlate { get; set; }
        [Display(Name = "Travel Distance")]
        public double TraveledDistance { get; set; }
        public string Image { get; set; }
        [Display(Name = "Status")]
        public string Status { get; set; }
        public int StatusNum { get; set; }
    }
}

GymApp/Controllers/VehicleController.cs
using GymApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GymApp.Controllers
{
    public class VehicleController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Vehicle
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddVehicle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddVehicle(Vehicle model, HttpPostedFileBase file)
        {
            //check if a file was uploaded
            if (file != null && file.ContentLength > 0)
            {
                //get file extension
                string ext = file.ContentType.ToLower();
                //verify extension
                if (ext != "image/jpg" &&
                    ext != "image/jpeg" &&
                    ext != "image/pjpeg" &&
                    ext != "image/gif" &&
                    ext != "image/x-png" &&
                    ext != "image/png")
                {
                    ModelState.AddModelError("", "Wrong Image format !");
                    return View(model);
                }
            }

            using (var db = new ApplicationDbContext())
            {
                // Check if the number plate already exists
                if (db.Vehicles.Any(v => v.NumberPlate == model.NumberPlate))
                {
                    ModelState.AddModelError("", "Number Plate already exists!");
                    return View(model);
                }

                Vehicle g = new Vehicle()
                {
                    VehicleName = model.VehicleName,
                    VehicleColor = model.VehicleColor,
                    NumberPlate = model.NumberPlate,
                    Image = file.FileName,
                    Status = "Available",
                    TraveledDistance = 0,
                    StatusNum = 1,
                };

                db.Vehicles.Add(g);
                db.SaveChanges();

                int id = g.Id;

                #region add image

                //create necessary directories
                var dir = new DirectoryInfo(string.Format("{0}Images\\Uploads", Server.MapPath(@"\")));
                var pathString1 = Path.Combine(dir.ToString(), "Vehicles");
                var pathString2 = Path.Combine(dir.ToString(), "Vehicles\\" + id.ToString());

                if (!Directory.Exists(pathString1))
                {
                    Directory.CreateDirectory(pathString1);
                }

                if (!Directory.Exists(pathString2))
                {
                    Directory.CreateDirectory(pathString2);
                }

                //initilize image name
                string imageName = file.FileName;

                var path = string.Format("{0}\\{1}", pathString2, imageName);

                //save original image
                file.SaveAs(path);

                #endregion

                return Redirect("/Vehicle/VehicleList");
            }
        }
        public ActionResult VehicleList()
        {
            return View(db.Vehicles.ToList());
        }
        public ActionResult ManageVehicles()
        {
            return View();
        }
    }
}

GymApp/Views/Vehicle/AddVehicle.cshtml
@model GymApp.Models.Vehicle
@{
    ViewBag.Title = "AddVehicle";
    Layout = "~/Views/Shared/_LayoutAdminPage.cshtml";
}

<div class="content-wrapper">
    <h4 class="title">New Vehicle</h4>
    <p>Add new vehicle to be assigned to drivers.</p>
    <hr />
    @using (Html.BeginForm("AddVehicle", "Vehicle", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.VehicleName, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.VehicleName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VehicleName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VehicleColor, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.VehicleColor, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VehicleColor, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NumberPlate, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.NumberPlate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NumberPlate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" class="form-control" name="file" required />
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add vehicle" class="btn btn-success" />
                </div>
            </div>
        </div>

    }
</div>

GymApp/Views/Vehicle/VehicleList.cshtml
@model IEnumerable<GymApp.Models.Vehicle>
@{
    ViewBag.Title = "VehicleList";
    Layout = "~/Views/Shared/_LayoutAdminPage.cshtml";
}

<div class="content-wrapper">
    <h5 class="title">Vehicles</h5>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Color</th>
                <th>Number Plate</th>
                <th>Traveled Distansce</th>
                <th>Status</th>
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="5">
                        <p class="text-center m-0">No Records Found</p>
                    </td>
                </tr>
            }
            else
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.VehicleName</td>
                        <td>@item.VehicleColor</td>
                        <td>@item.NumberPlate</td>
                        <td>@item.TraveledDistance KM</td>
                        <td>@item.Status</td>
                        <td>
                            @if (!string.IsNullOrEmpty(item.Image))
                            {
                                <img src="~/Images/Uploads/Vehicles/@item.Id/@item.Image" alt="Vehicle Image" style="width: 145px; height: 145px;" />
                            }
                            else
                            {
                                <p>No Image Available</p>
                            }
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>